#ifndef PUBSUB_H
#define PUBSUB_H

#include <stddef.h>
#include <stdint.h>

typedef enum {
	// --- System ---
	LOOP = 0,
	SCHEDULER_1HZ,
	SCHEDULER_5HZ,
	SCHEDULER_10HZ,
	SCHEDULER_25HZ,
	SCHEDULER_50HZ,
	SCHEDULER_100HZ,
	SCHEDULER_250HZ,
	SCHEDULER_500HZ,
	SCHEDULER_1KHZ,
	SCHEDULER_2KHZ,
	SCHEDULER_4KHZ,
	SCHEDULER_8KHZ,

	// --- Hardware callbacks ---
	I2C_CALLBACK_UPDATE,
	SPI_CALLBACK_UPDATE,

	// --- UART / protocol ---
	UART_RAW_RECEIVED,
	UART_RAW_SEND,
	UART_TX_COMPLETE,
	DB_MESSAGE_UPDATE,
	UBX_MESSAGE_UPDATE,

	// --- IMU ---
	SENSOR_IMU1_GYRO_UPDATE,
	SENSOR_IMU1_GYRO_FILTERED_UPDATE,
	SENSOR_IMU1_ACCEL_UPDATE,

	// --- Other sensors ---
	SENSOR_COMPASS,
	SENSOR_AIR_PRESSURE,
	EXTERNAL_SENSOR_GPS,
	EXTERNAL_SENSOR_GPS_VELOC,
	EXTERNAL_SENSOR_GPS_QUALITY,
	EXTERNAL_SENSOR_OPTFLOW,

	// --- Estimation / fusion ---
	ANGULAR_STATE_UPDATE,
	LINEAR_ACCEL_UPDATE,
	POSITION_STATE_UPDATE,

	// --- Control ---
	ANGULAR_TARGET_UPDATE,
	POSITION_TARGET_UPDATE,
	ALTITUDE_CONTROL_UPDATE,
	MIX_CONTROL_UPDATE,
	SPEED_CONTROL_SETUP,
	SPEED_CONTROL_UPDATE,

	// --- Flight state & RC ---
	FLIGHT_STATE_UPDATE,
	RC_STATE_UPDATE,
	RC_MOVE_IN_UPDATE,

	// --- Calibration ---
	CALIBRATION_GYRO_REQUEST,
	CALIBRATION_ACCEL_REQUEST,
	CALIBRATION_MAG_REQUEST,
	CALIBRATION_GYRO_READY,
	CALIBRATION_ACCEL_READY,
	CALIBRATION_MAG_READY,
	CALIBRATION_GYRO_STATUS,
	CALIBRATION_ACCEL_STATUS,
	CALIBRATION_MAG_STATUS,

	// --- Storage ---
	LOCAL_STORAGE_LOAD,
	LOCAL_STORAGE_RESULT,
	LOCAL_STORAGE_SAVE,

	// --- Health & fault ---
	FAULT_DETECTION,
	SENSOR_HEALTH_UPDATE,
	SENSOR_HEALTH_REQUEST,

	// --- Logging / telemetry ---
	NOTIFY_LOG_CLASS,
	SEND_LOG,
	FFT_PEAKS_UPDATE,

	TOPIC_NULL
} topic_t;

typedef void (*subscriber_callback_t)(uint8_t *data, size_t size);

void publish(topic_t topic, uint8_t *data, size_t size);
void subscribe(topic_t topic, subscriber_callback_t callback);

#endif
